//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSApplication.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DreamBDEntities : DbContext
    {
        public DreamBDEntities()
            : base("name=DreamBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CBLoginInfo> CBLoginInfoes { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
    
        public virtual ObjectResult<string> GetCBLoginInfo(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCBLoginInfo", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Usp_Ins_CBLoginInfo(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Usp_Ins_CBLoginInfo", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Usp_Sel_CBLoginInfoList_Result> Usp_Sel_CBLoginInfoList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_CBLoginInfoList_Result>("Usp_Sel_CBLoginInfoList");
        }
    
        public virtual ObjectResult<Usp_Sel_MenuList_Result> Usp_Sel_MenuList(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_MenuList_Result>("Usp_Sel_MenuList", customerIdParameter);
        }
    
        public virtual ObjectResult<Usp_Sel_SubmenuList_Result> Usp_Sel_SubmenuList(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_SubmenuList_Result>("Usp_Sel_SubmenuList", customerIdParameter);
        }
    }
}
