//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSApplication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string SubmenuName { get; set; }
        public string MenuIcon { get; set; }
        public string SubmenuIcon { get; set; }
        public string Link { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
    }
}
